#!/usr/bin/env python3
"""Reconcile a Harness-owned CodeDeploy workflow only when its contract changed."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


MARKER = "# Generated by harness-codex CodeDeploy pipeline."


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--pipeline", choices=("codedeploy", "none"), required=True)
    parser.add_argument("--appspec", default="appspec.yml")
    parser.add_argument("--package-command", default='zip -r "$REVISION_FILE" . -x ".git/*" ".harness/*"')
    parser.add_argument("--health-path", default="/")
    parser.add_argument("--app-port", type=int, default=8080)
    parser.add_argument("--branch", default="main")
    options = parser.parse_args()

    root = Path(options.repo_root).resolve()
    workflow = root / ".github/workflows/codedeploy.yml"
    evidence = root / ".harness/runs" / options.run_id / "codedeploy-gate.json"

    if options.pipeline == "none":
        return _finish(evidence, "skipped", workflow, "Deployment Pipeline is none")
    appspec = (root / options.appspec).resolve()
    if root != appspec and root not in appspec.parents:
        return _finish(evidence, "conflict", workflow, "AppSpec path escapes repository", 2)
    if not appspec.is_file():
        return _finish(evidence, "conflict", workflow, f"AppSpec is missing: {options.appspec}", 2)

    contract = {
        "appspec": Path(options.appspec).as_posix(),
        "branch": options.branch,
        "health_path": options.health_path,
        "app_port": str(options.app_port),
        "package_command": options.package_command,
        "revision_file": "${{ runner.temp }}/revision.zip",
    }
    fingerprint = hashlib.sha256(
        json.dumps(contract, ensure_ascii=False, sort_keys=True).encode("utf-8")
    ).hexdigest()
    desired = _workflow(contract, fingerprint)

    if workflow.is_file():
        current = workflow.read_text(encoding="utf-8")
        if current == desired:
            return _finish(evidence, "unchanged", workflow, "deployment contract is unchanged")
        if MARKER not in current:
            return _finish(evidence, "conflict", workflow, "existing workflow is user-owned", 2)
        status = "updated"
    else:
        status = "created"

    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(desired, encoding="utf-8")
    return _finish(evidence, status, workflow, "deployment contract changed")


def _finish(evidence: Path, status: str, workflow: Path, reason: str, code: int = 0) -> int:
    evidence.parent.mkdir(parents=True, exist_ok=True)
    payload = {"status": status, "workflow": str(workflow), "reason": reason}
    evidence.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False))
    return code


def _workflow(contract: dict[str, str], fingerprint: str) -> str:
    package = "\n".join(f"          {line}" for line in contract["package_command"].splitlines())
    return f'''{MARKER}
# harness-codedeploy-fingerprint: {fingerprint}
name: Deploy with CodeDeploy

on:
  push:
    branches: [{contract["branch"]}]

permissions:
  contents: read
  id-token: write

concurrency:
  group: codedeploy-${{{{ github.ref }}}}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{{{ vars.AWS_REGION }}}}
      APP_PORT: "{contract["app_port"]}"
      HEALTH_PATH: "{contract["health_path"]}"
      REVISION_FILE: ${{{{ runner.temp }}}}/revision.zip
      REVISION_KEY: revisions/${{{{ github.sha }}}}.zip
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{{{ env.AWS_REGION }}}}
          role-to-assume: ${{{{ vars.AWS_DEPLOY_ROLE_ARN }}}}
      - id: readiness
        name: Check EC2 readiness
        shell: bash
        run: |
          state="$(aws ec2 describe-instances --instance-ids "${{{{ vars.EC2_INSTANCE_ID }}}}" --query 'Reservations[0].Instances[0].State.Name' --output text)"
          if [[ "$state" == "stopped" || "$state" == "stopping" ]]; then
            echo "::notice::CodeDeploy skipped because EC2 is $state"
            echo "deploy=false" >> "$GITHUB_OUTPUT"
          elif [[ "$state" == "running" ]]; then
            echo "deploy=true" >> "$GITHUB_OUTPUT"
            public_dns="$(aws ec2 describe-instances --instance-ids "${{{{ vars.EC2_INSTANCE_ID }}}}" --query 'Reservations[0].Instances[0].PublicDnsName' --output text)"
            if [[ -z "$public_dns" || "$public_dns" == "None" ]]; then
              echo "EC2 public DNS is unavailable" >&2
              exit 1
            fi
            echo "public_dns=$public_dns" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported EC2 state: $state" >&2
            exit 1
          fi
      - name: Package revision
        if: steps.readiness.outputs.deploy == 'true'
        shell: bash
        run: |
{package}
      - name: Upload revision
        if: steps.readiness.outputs.deploy == 'true'
        run: aws s3 cp "$REVISION_FILE" "s3://${{{{ vars.CODEDEPLOY_BUCKET }}}}/$REVISION_KEY"
      - id: deployment
        name: Create deployment
        if: steps.readiness.outputs.deploy == 'true'
        shell: bash
        run: |
          deployment_id="$(aws deploy create-deployment \\
            --application-name "${{{{ vars.CODEDEPLOY_APPLICATION }}}}" \\
            --deployment-group-name "${{{{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }}}}" \\
            --revision "revisionType=S3,s3Location={{bucket=${{{{ vars.CODEDEPLOY_BUCKET }}}},key=$REVISION_KEY,bundleType=zip}}" \\
            --query deploymentId --output text)"
          echo "deployment_id=$deployment_id" >> "$GITHUB_OUTPUT"
      - name: Wait for deployment
        if: steps.readiness.outputs.deploy == 'true'
        run: aws deploy wait deployment-successful --deployment-id "${{{{ steps.deployment.outputs.deployment_id }}}}"
      - name: Verify public endpoints
        if: steps.readiness.outputs.deploy == 'true'
        shell: bash
        run: |
          base_url="http://${{{{ steps.readiness.outputs.public_dns }}}}:$APP_PORT"
          curl --fail --show-error --retry 10 --retry-delay 3 "$base_url/"
          if [[ "$HEALTH_PATH" != "/" ]]; then
            curl --fail --show-error --retry 10 --retry-delay 3 "$base_url/${{HEALTH_PATH#/}}"
          fi
'''


if __name__ == "__main__":
    raise SystemExit(main())
