"""Terraform-only AWS application infrastructure initialization."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Sequence


GENERATOR_MARKER = "# Generated by harness-codex app infrastructure."
TERRAFORM_ROOT = Path("infra/harness/aws")


def scaffold_app_runtime(repo_root: Path | str, args: Sequence[str]) -> str:
    """Generate CodeDeploy-ready AWS Terraform and initialize its providers."""

    root = Path(repo_root).resolve()
    parser = argparse.ArgumentParser(prog="harness run app init", add_help=False)
    parser.add_argument("--force", action="store_true")
    try:
        options = parser.parse_args(list(args))
    except SystemExit as exc:
        raise ValueError("usage: harness run app init [--force]") from exc

    created: list[Path] = []
    preserved: list[Path] = []
    for relative, content in _terraform_files().items():
        if _write_generated(root / relative, content, force=options.force):
            created.append(relative)
        else:
            preserved.append(relative)

    source = root / TERRAFORM_ROOT
    _run_terraform(source, "init", "-input=false")
    _run_terraform(source, "validate")

    return "\n".join(
        [
            "AWS application infrastructure initialized:",
            f"- terraform: {TERRAFORM_ROOT}",
            *[f"- created: {path}" for path in created],
            *[f"- preserved: {path}" for path in preserved],
            "- terraform init: ok",
            "- terraform validate: ok",
            "- terraform plan/apply: not run",
            "Warning: Elastic IP, public IPv4, EBS, S3, and other AWS resources may incur charges after apply.",
        ]
    )


def _write_generated(path: Path, content: str, *, force: bool) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8", errors="ignore")
        if not force or GENERATOR_MARKER not in current:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _run_terraform(source: Path, *args: str) -> None:
    try:
        completed = subprocess.run(
            ["terraform", f"-chdir={source}", *args],
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise ValueError("terraform is required for `harness run app init`") from exc
    if completed.returncode:
        detail = (completed.stderr or completed.stdout).strip()
        suffix = f": {detail}" if detail else ""
        raise ValueError(f"terraform {' '.join(args)} failed{suffix}")


def _terraform_files() -> dict[Path, str]:
    base = TERRAFORM_ROOT
    return {
        base / ".gitignore": f"""{GENERATOR_MARKER}
.terraform/
*.tfstate
*.tfstate.*
*.tfplan
crash.log
""",
        base / "versions.tf": f"""{GENERATOR_MARKER}
terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }}
  }}
}}
""",
        base / "variables.tf": f"""{GENERATOR_MARKER}
variable "aws_region" {{
  description = "AWS region for the application infrastructure."
  type        = string
  default     = "ap-northeast-2"
}}

variable "aws_profile" {{
  description = "Optional local AWS CLI profile. Leave empty in GitHub Actions."
  type        = string
  default     = ""
}}

variable "project_name" {{
  description = "Lowercase identifier used in AWS resource names."
  type        = string
}}

variable "app_port" {{
  description = "Public HTTP port exposed by the application."
  type        = number
  default     = 8080
}}

variable "instance_type" {{
  description = "EC2 instance type selected after checking current Free Tier eligibility."
  type        = string
  default     = "t3.micro"
}}

variable "github_oidc_subjects" {{
  description = "Exact GitHub OIDC sub claims allowed to deploy from main. Prefer immutable repository IDs for new repositories."
  type        = list(string)
}}
""",
        base / "main.tf": f"""{GENERATOR_MARKER}
provider "aws" {{
  region  = var.aws_region
  profile = var.aws_profile == "" ? null : var.aws_profile
}}

data "aws_caller_identity" "current" {{}}

data "aws_ssm_parameter" "al2023_ami" {{
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}}

resource "aws_vpc" "app" {{
  cidr_block           = "10.93.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags                 = {{ Name = "${{var.project_name}}-harness" }}
}}

resource "aws_internet_gateway" "app" {{
  vpc_id = aws_vpc.app.id
  tags   = {{ Name = "${{var.project_name}}-harness" }}
}}

resource "aws_subnet" "public" {{
  vpc_id                  = aws_vpc.app.id
  cidr_block              = "10.93.1.0/24"
  map_public_ip_on_launch = false
  tags                    = {{ Name = "${{var.project_name}}-harness-public" }}
}}

resource "aws_route_table" "public" {{
  vpc_id = aws_vpc.app.id
  route {{
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.app.id
  }}
  tags = {{ Name = "${{var.project_name}}-harness-public" }}
}}

resource "aws_route_table_association" "public" {{
  subnet_id      = aws_subnet.public.id
  route_table_id = aws_route_table.public.id
}}

resource "aws_security_group" "app" {{
  name_prefix = "${{var.project_name}}-harness-"
  vpc_id      = aws_vpc.app.id

  ingress {{
    description = "Public application HTTP"
    from_port   = var.app_port
    to_port     = var.app_port
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{ Name = "${{var.project_name}}-harness-app" }}
}}

resource "aws_iam_role" "instance" {{
  name = "${{var.project_name}}-harness-instance"
  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Effect    = "Allow"
      Principal = {{ Service = "ec2.amazonaws.com" }}
      Action    = "sts:AssumeRole"
    }}]
  }})
}}

resource "aws_iam_role_policy_attachment" "instance_ssm" {{
  role       = aws_iam_role.instance.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}}

resource "aws_iam_instance_profile" "app" {{
  name = "${{var.project_name}}-harness-instance"
  role = aws_iam_role.instance.name
}}

resource "aws_s3_bucket" "revisions" {{
  bucket        = "${{var.project_name}}-codedeploy-${{data.aws_caller_identity.current.account_id}}-${{var.aws_region}}"
  force_destroy = true
  tags          = {{ ManagedBy = "harness-codex" }}
}}

resource "aws_s3_bucket_public_access_block" "revisions" {{
  bucket                  = aws_s3_bucket.revisions.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

resource "aws_iam_role_policy" "instance_revisions" {{
  name = "codedeploy-revisions"
  role = aws_iam_role.instance.id
  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Effect   = "Allow"
      Action   = ["s3:GetObject", "s3:GetObjectVersion", "s3:ListBucket"]
      Resource = [aws_s3_bucket.revisions.arn, "${{aws_s3_bucket.revisions.arn}}/*"]
    }}]
  }})
}}

resource "aws_instance" "app" {{
  ami                         = data.aws_ssm_parameter.al2023_ami.value
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.public.id
  vpc_security_group_ids      = [aws_security_group.app.id]
  iam_instance_profile        = aws_iam_instance_profile.app.name
  associate_public_ip_address = false
  metadata_options {{
    http_endpoint = "enabled"
    http_tokens   = "required"
  }}
  root_block_device {{
    volume_size           = 8
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }}
  user_data = <<-EOF
    #!/bin/bash
    set -euxo pipefail
    dnf install -y ruby wget
    cd /tmp
    wget "https://aws-codedeploy-${{var.aws_region}}.s3.${{var.aws_region}}.amazonaws.com/latest/install"
    chmod +x install
    ./install auto
    systemctl enable --now codedeploy-agent
    systemctl enable --now amazon-ssm-agent
  EOF
  tags = {{
    Name       = "${{var.project_name}}-harness-app"
    ManagedBy  = "harness-codex"
    CodeDeploy = var.project_name
  }}
}}

resource "aws_eip" "app" {{
  domain = "vpc"
  tags   = {{ Name = "${{var.project_name}}-harness-app" }}
}}

resource "aws_eip_association" "app" {{
  instance_id   = aws_instance.app.id
  allocation_id = aws_eip.app.id
}}

data "aws_instance" "app" {{
  instance_id = aws_instance.app.id
  depends_on  = [aws_eip_association.app]
}}

resource "aws_iam_role" "codedeploy" {{
  name = "${{var.project_name}}-harness-codedeploy"
  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Effect    = "Allow"
      Principal = {{ Service = "codedeploy.amazonaws.com" }}
      Action    = "sts:AssumeRole"
    }}]
  }})
}}

resource "aws_iam_role_policy_attachment" "codedeploy" {{
  role       = aws_iam_role.codedeploy.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
}}

resource "aws_codedeploy_app" "app" {{
  compute_platform = "Server"
  name             = var.project_name
}}

resource "aws_codedeploy_deployment_group" "app" {{
  app_name               = aws_codedeploy_app.app.name
  deployment_group_name  = "${{var.project_name}}-main"
  service_role_arn       = aws_iam_role.codedeploy.arn
  deployment_config_name = "CodeDeployDefault.OneAtATime"
  ec2_tag_filter {{
    key   = "CodeDeploy"
    type  = "KEY_AND_VALUE"
    value = var.project_name
  }}
}}

resource "aws_iam_openid_connect_provider" "github" {{
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = ["6938fd4d98bab03faadb97b34396831e3780aea1"]
}}

resource "aws_iam_role" "github_deploy" {{
  name = "${{var.project_name}}-harness-github-deploy"
  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Effect    = "Allow"
      Principal = {{ Federated = aws_iam_openid_connect_provider.github.arn }}
      Action    = "sts:AssumeRoleWithWebIdentity"
      Condition = {{
        StringEquals = {{
          "token.actions.githubusercontent.com:aud" = "sts.amazonaws.com"
          "token.actions.githubusercontent.com:sub" = var.github_oidc_subjects
        }}
      }}
    }}]
  }})
}}

resource "aws_iam_role_policy" "github_deploy" {{
  name = "codedeploy-main"
  role = aws_iam_role.github_deploy.id
  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Effect   = "Allow"
        Action   = ["s3:PutObject"]
        Resource = ["${{aws_s3_bucket.revisions.arn}}/*"]
      }},
      {{
        Effect   = "Allow"
        Action   = ["codedeploy:CreateDeployment", "codedeploy:GetDeployment", "codedeploy:GetDeploymentConfig"]
        Resource = "*"
      }},
      {{
        Effect   = "Allow"
        Action   = ["ec2:DescribeInstances"]
        Resource = "*"
      }}
    ]
  }})
}}
""",
        base / "outputs.tf": f"""{GENERATOR_MARKER}
output "instance_id" {{ value = aws_instance.app.id }}
output "elastic_ip" {{ value = aws_eip.app.public_ip }}
output "public_dns" {{ value = data.aws_instance.app.public_dns }}
output "public_url" {{ value = "http://${{data.aws_instance.app.public_dns}}:${{var.app_port}}/" }}
output "revision_bucket" {{ value = aws_s3_bucket.revisions.bucket }}
output "codedeploy_application" {{ value = aws_codedeploy_app.app.name }}
output "codedeploy_deployment_group" {{ value = aws_codedeploy_deployment_group.app.deployment_group_name }}
output "github_deploy_role_arn" {{ value = aws_iam_role.github_deploy.arn }}
""",
    }
