"""Local UI session helpers for harvest requirements and use-case generation."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tomllib
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any
from uuid import uuid4

from harness_codex.runtime.models import RunContext, RunMode, Step, StepKind
from harness_codex.runtime.prompt import build_agent_prompt

SESSION_PATH = Path(".harness/ui/harvest-session.json")
CHANGESET_SESSION_ROOT = Path(".harness/ui/change-sets")
REQUIREMENTS_PATH = Path("docs/design/요구사항.md")
CONTEXT_PATH = Path("context.md")
USE_CASES_PATH = Path("docs/design/유스케이스.md")
USE_CASE_SLICE_ROOT = Path("docs/use-cases")
GRILL_ME_SKILL_PATH = Path(".codex/skills/grill-me/SKILL.md")
REQUIREMENTS_SKILL_PATH = Path(".codex/skills/harness-requirements/SKILL.md")
USE_CASE_AGENT_CONFIG_PATH = Path(".codex/agents/harness_usecases.toml")
USE_CASE_SKILL_PATH = Path(".codex/skills/harness-usecases/SKILL.md")
USE_CASE_DEFINITION_TIMEOUT_SEC = 3600
EVENT_STORMING_AGENT_CONFIG_PATH = Path(".codex/agents/oracle.toml")
EVENT_STORMING_SKILL_PATH = Path(".codex/skills/harness-event-storming/SKILL.md")
EVENT_STORMING_TIMEOUT_SEC = 3600
DDD_AGENT_CONFIG_PATH = Path(".codex/agents/ddd_architect.toml")
DDD_SKILL_PATH = Path(".codex/skills/harness-ddd-design/SKILL.md")
DDD_TIMEOUT_SEC = 3600
DDD_STEPS = (
    ("entity_vo", "Entity / Value Objects"),
    ("behaviors", "Behaviors"),
    ("application_flow", "Application Flow"),
    ("aggregates", "Aggregates"),
    ("bounded_contexts", "Bounded Contexts"),
)


@dataclass(frozen=True)
class HarvestUiResult:
    initial_prompt: str
    status: str
    active_stage: str
    requirements_markdown: str
    use_cases_markdown: str
    clarifications: tuple[dict[str, Any], ...]
    current_question: dict[str, Any] | None
    current_questions: tuple[dict[str, Any], ...]
    requirements_gate_passed: bool
    use_cases_ready: bool
    event_storming: dict[str, Any]
    ddd_architecture: dict[str, Any]
    runtime_error: str
    workflow: dict[str, Any]

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def start_requirements(root: Path | str, prompt: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _new_session(prompt)
    if not session["initial_prompt"]:
        raise ValueError("initial prompt is required")
    _write_session(root_path, session)
    _advance_grill_me(root_path, session)
    _write_context_doc(root_path, session)
    _write_requirements_doc(root_path, session)
    _write_session(root_path, session)
    return _result(root_path, session)


def answer_requirements(root: Path | str, answer: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    normalized_answer = answer.strip()
    if not normalized_answer:
        raise ValueError("answer is required")
    current_question = _current_question(session)
    if current_question is None:
        raise ValueError("no active Grill-Me question")
    session["clarifications"].append(
        {
            "questions": [
                {
                    "question": current_question.get("question", ""),
                    "recommended": current_question.get("recommended", ""),
                }
            ],
            "answer": normalized_answer,
        }
    )
    session["current_questions"] = []
    session["current_question"] = None
    session["pending_questions"] = []
    _advance_grill_me(root_path, session)
    _write_context_doc(root_path, session)
    _write_requirements_doc(root_path, session)
    _write_session(root_path, session)
    return _result(root_path, session)


def start_use_cases(root: Path | str) -> HarvestUiResult:
    """Mark use-case harvest complete only after runtime-ready slice docs exist.

    Interactive harvest used to write a local placeholder document here. That made
    the UI look complete while the repository was not ready for ChangeSet
    execution. Use-case docs are now generated by the same agent-backed path as
    apply harvest; this function only validates and records readiness.
    """

    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    if not session["requirements_gate_passed"]:
        raise ValueError("requirements gate has not passed")
    ready, error = _validate_runtime_ready_use_case_slices(root_path)
    if not ready:
        raise ValueError(error)
    session["active_stage"] = "useCases"
    session["use_cases_ready"] = True
    session["runtime_error"] = ""
    _write_session(root_path, session)
    return _result(root_path, session)


def start_use_case_generation(root: Path | str, idea: str = "") -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    if not session["requirements_gate_passed"]:
        raise ValueError("requirements gate has not passed")
    session["active_stage"] = "useCases"
    ready, _ = _validate_runtime_ready_use_case_slices(root_path)
    if ready:
        session["use_cases_ready"] = True
        session["runtime_error"] = ""
        _write_session(root_path, session)
        return _result(root_path, session)
    if _current_use_case_question(session) is None:
        _advance_use_case_harvest(root_path, session, idea)
    _write_session(root_path, session)
    return _result(root_path, session)


def answer_use_cases(root: Path | str, answer: str, idea: str = "") -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    if not session["requirements_gate_passed"]:
        raise ValueError("requirements gate has not passed")
    normalized_answer = answer.strip()
    if not normalized_answer:
        raise ValueError("answer is required")
    current_question = _current_use_case_question(session)
    if current_question is None:
        raise ValueError("no active use-case question")
    session["use_case_clarifications"].append(
        {
            "questions": [
                {
                    "question": current_question.get("question", ""),
                    "recommended": current_question.get("recommended", ""),
                }
            ],
            "answer": normalized_answer,
        }
    )
    session["use_case_current_question"] = None
    session["use_case_current_questions"] = []
    session["use_case_pending_questions"] = []
    _advance_use_case_harvest(root_path, session, idea)
    _write_session(root_path, session)
    return _result(root_path, session)


def start_event_storming(root: Path | str, change_set_id: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    if not session.get("use_cases_ready"):
        raise ValueError("use-case gate has not passed")
    uc_ids = _parse_canonical_use_case_ids(_read_optional(root_path / USE_CASES_PATH))
    if not uc_ids:
        raise ValueError("no generated use-case slices are available for event storming")
    state = session.get("event_storming")
    if not isinstance(state, dict) or state.get("uc_ids") != uc_ids:
        state = _new_event_storming_state(uc_ids)
        session["event_storming"] = state
    session["active_stage"] = "eventStorming"
    if not state.get("complete") and not _current_event_storming_question(session):
        _advance_event_storming(root_path, session, change_set_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def advance_event_storming(root: Path | str, change_set_id: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    if not session.get("use_cases_ready"):
        raise ValueError("use-case gate has not passed")
    state = session.get("event_storming")
    if not isinstance(state, dict):
        raise ValueError("event storming has not started")
    if _current_event_storming_question(session):
        raise ValueError("answer the current event-storming question before continuing")
    _advance_event_storming(root_path, session, change_set_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def answer_event_storming(
    root: Path | str,
    change_set_id: str,
    uc_id: str,
    answer: str,
) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    state = session.get("event_storming")
    if not isinstance(state, dict) or state.get("current_uc") != uc_id:
        raise ValueError("no active event-storming question for use case")
    item = state.get("items", {}).get(uc_id, {})
    question = item.get("current_question")
    normalized_answer = answer.strip()
    if not isinstance(question, dict) or not normalized_answer:
        raise ValueError("answer is required for the current event-storming question")
    item.setdefault("clarifications", []).append(
        {
            "questions": [
                {
                    "question": str(question.get("question", "")),
                    "recommended": str(question.get("recommended", "")),
                }
            ],
            "answer": normalized_answer,
        }
    )
    item["current_question"] = None
    _advance_event_storming(root_path, session, change_set_id, uc_id=uc_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def start_ddd_architecture(root: Path | str, change_set_id: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    event_state = session.get("event_storming")
    if not isinstance(event_state, dict) or not event_state.get("complete"):
        raise ValueError("event-storming gate has not passed")
    uc_ids = [
        uc_id for uc_id in event_state.get("uc_ids", [])
        if event_state.get("items", {}).get(uc_id, {}).get("status") == "complete"
    ]
    if not uc_ids:
        raise ValueError("no completed event-storming slices are available for DDD architecture")
    state = session.get("ddd_architecture")
    if not isinstance(state, dict) or state.get("uc_ids") != uc_ids:
        state = _new_ddd_architecture_state(uc_ids)
        session["ddd_architecture"] = state
    session["active_stage"] = "dddArchitecture"
    if not state.get("complete") and not _current_ddd_question(session):
        _advance_ddd_architecture(root_path, session, change_set_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def restart_ddd_architecture(root: Path | str, change_set_id: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    event_state = session.get("event_storming")
    if not isinstance(event_state, dict) or not event_state.get("complete"):
        raise ValueError("event-storming gate has not passed")
    uc_ids = [
        uc_id
        for uc_id in event_state.get("uc_ids", [])
        if event_state.get("items", {}).get(uc_id, {}).get("status") == "complete"
    ]
    if not uc_ids:
        raise ValueError("no completed event-storming slices are available for DDD architecture")
    for uc_id in uc_ids:
        output = root_path / USE_CASE_SLICE_ROOT / uc_id / "ddd-design.md"
        if output.exists():
            output.unlink()
    architecture = root_path / "ARCHITECTURE.md"
    if architecture.exists():
        architecture.unlink()
    session["ddd_architecture"] = _new_ddd_architecture_state(uc_ids)
    session["active_stage"] = "dddArchitecture"
    session["runtime_error"] = ""
    _advance_ddd_architecture(root_path, session, change_set_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def advance_ddd_architecture(root: Path | str, change_set_id: str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    state = session.get("ddd_architecture")
    if not isinstance(state, dict):
        raise ValueError("DDD architecture has not started")
    if _current_ddd_question(session):
        raise ValueError("answer the current DDD architecture question before continuing")
    _advance_ddd_architecture(root_path, session, change_set_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def rerun_ddd_architecture_step(
    root: Path | str,
    change_set_id: str,
    uc_id: str,
    step_id: str,
    user_prompt: str,
) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    state = session.get("ddd_architecture")
    if not isinstance(state, dict):
        raise ValueError("DDD architecture has not started")
    if _current_ddd_question(session):
        raise ValueError("answer the current DDD architecture question before rerunning a substep")
    item = state.get("items", {}).get(uc_id)
    if not isinstance(item, dict) or step_id not in item.get("steps", {}):
        raise ValueError("unknown DDD architecture substep")
    normalized_prompt = user_prompt.strip()
    if not normalized_prompt:
        raise ValueError("rerun prompt is required")
    step_ids = [current_id for current_id, _label in DDD_STEPS]
    target_index = step_ids.index(step_id)
    for current_id in step_ids[target_index + 1 :]:
        current = item["steps"][current_id]
        if current.get("status") == "complete":
            current["status"] = "stale"
    item["steps"][step_id].setdefault("rerun_prompts", []).append(normalized_prompt)
    item["steps"][step_id]["current_question"] = None
    state["complete"] = False
    state["status"] = "running"
    item["status"] = "running"
    session["active_stage"] = "dddArchitecture"
    _advance_ddd_architecture(root_path, session, change_set_id, uc_id=uc_id, step_id=step_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def answer_ddd_architecture(
    root: Path | str,
    change_set_id: str,
    uc_id: str,
    step_id: str,
    answer: str,
) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_or_recover_session(root_path)
    state = session.get("ddd_architecture")
    if not isinstance(state, dict) or state.get("current_uc") != uc_id:
        raise ValueError("no active DDD architecture question for use case")
    item = state.get("items", {}).get(uc_id, {})
    step = item.get("steps", {}).get(step_id, {})
    question = step.get("current_question")
    normalized_answer = answer.strip()
    if step_id != state.get("current_step") or not isinstance(question, dict) or not normalized_answer:
        raise ValueError("answer is required for the current DDD architecture question")
    step.setdefault("clarifications", []).append(
        {
            "questions": [{"question": str(question.get("question", "")), "recommended": str(question.get("recommended", ""))}],
            "answer": normalized_answer,
        }
    )
    step["current_question"] = None
    _advance_ddd_architecture(root_path, session, change_set_id, uc_id=uc_id, step_id=step_id)
    _write_session(root_path, session)
    return _result(root_path, session)


def load_harvest_ui(root: Path | str) -> HarvestUiResult:
    root_path = Path(root)
    session = _load_session(root_path)
    if session is None:
        session = _session_from_requirements_doc(root_path)
    if session is None:
        session = _new_session("")
    else:
        _normalize_session(session)
        _sync_use_case_readiness(root_path, session)
        _resume_if_needed(root_path, session)
    return _result(root_path, session)


def save_changeset_harvest_ui(root: Path | str, change_set_id: str) -> None:
    root_path = Path(root)
    _require_active_changeset(root_path, change_set_id)
    session = _load_session(root_path)
    if session is None:
        raise ValueError("harvest session has not started")
    _write_changeset_harvest_snapshot(root_path, change_set_id, session)


def _write_changeset_harvest_snapshot(root: Path, change_set_id: str, session: dict[str, Any]) -> None:
    scoped_root = _changeset_session_root(root, change_set_id)
    scoped_root.mkdir(parents=True, exist_ok=True)
    (scoped_root / "harvest-session.json").write_text(
        json.dumps(session, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    for artifact in (REQUIREMENTS_PATH, CONTEXT_PATH):
        _copy_optional_artifact(root / artifact, scoped_root / artifact)
    use_cases_started = (
        session.get("active_stage") == "useCases"
        or session.get("use_cases_ready")
        or session.get("use_case_current_question")
        or session.get("use_case_clarifications")
    )
    if use_cases_started:
        _copy_optional_artifact(root / USE_CASES_PATH, scoped_root / USE_CASES_PATH)
        _copy_scoped_use_case_outputs(root, scoped_root, session)
        if isinstance(session.get("ddd_architecture"), dict):
            _copy_optional_artifact(root / "ARCHITECTURE.md", scoped_root / "ARCHITECTURE.md")
    else:
        use_case_document = scoped_root / USE_CASES_PATH
        if use_case_document.exists():
            use_case_document.unlink()
        use_case_slices = scoped_root / USE_CASE_SLICE_ROOT
        if use_case_slices.exists():
            shutil.rmtree(use_case_slices)


def load_changeset_harvest_ui(root: Path | str, change_set_id: str) -> HarvestUiResult:
    root_path = Path(root)
    _require_active_changeset(root_path, change_set_id)
    scoped_root = _changeset_session_root(root_path, change_set_id)
    session_path = scoped_root / "harvest-session.json"
    if not session_path.exists():
        session = _recover_changeset_session(root_path, change_set_id)
        _write_changeset_harvest_snapshot(root_path, change_set_id, session)
    else:
        session = json.loads(session_path.read_text(encoding="utf-8"))
    _normalize_session(session)
    _normalize_resumed_stage(session)
    return _result(root_path, session, artifact_root=scoped_root)


def activate_changeset_harvest_ui(root: Path | str, change_set_id: str) -> None:
    root_path = Path(root)
    load_changeset_harvest_ui(root_path, change_set_id)
    scoped_root = _changeset_session_root(root_path, change_set_id)
    session_path = scoped_root / "harvest-session.json"
    _copy_optional_artifact(session_path, root_path / SESSION_PATH)
    for artifact in (REQUIREMENTS_PATH, CONTEXT_PATH, USE_CASES_PATH):
        _copy_optional_artifact(scoped_root / artifact, root_path / artifact)
    _copy_optional_tree(
        scoped_root / USE_CASE_SLICE_ROOT,
        root_path / USE_CASE_SLICE_ROOT,
        replace=False,
    )


def _new_session(prompt: str) -> dict[str, Any]:
    return {
        "initial_prompt": prompt.strip(),
        "clarifications": [],
        "current_question": None,
        "current_questions": [],
        "pending_questions": [],
        "requirements_gate_passed": False,
        "active_stage": "requirements",
        "use_cases_ready": False,
        "runtime_error": "",
        "draft_context_markdown": "",
        "draft_requirements_markdown": "",
        "use_case_clarifications": [],
        "use_case_current_question": None,
        "use_case_current_questions": [],
        "use_case_pending_questions": [],
        "event_storming": None,
        "ddd_architecture": None,
    }


def _workflow_projection() -> dict[str, Any]:
    return {
        "stages": [
            {"id": "requirements", "label": "Requirements", "document": str(REQUIREMENTS_PATH)},
            {"id": "useCases", "label": "Use Cases", "document": str(USE_CASES_PATH)},
            {"id": "eventStorming", "label": "Event Storming", "document": ""},
            {"id": "dddArchitecture", "label": "DDD Architecture", "document": ""},
        ]
    }


def _load_or_recover_session(root: Path) -> dict[str, Any]:
    session = _load_session(root)
    if session is None:
        session = _session_from_requirements_doc(root)
    if session is None:
        raise ValueError("harvest session has not started")
    _normalize_session(session)
    _sync_use_case_readiness(root, session)
    return session


def _normalize_session(session: dict[str, Any]) -> None:
    session["clarifications"] = [
        _normalize_clarification(item)
        for item in session.get("clarifications", [])
    ]
    session.setdefault("pending_questions", [])
    session.setdefault("draft_context_markdown", "")
    session.setdefault("draft_requirements_markdown", "")
    session.setdefault("use_case_clarifications", [])
    session.setdefault("use_case_current_question", None)
    session.setdefault("use_case_current_questions", [])
    session.setdefault("use_case_pending_questions", [])
    session.setdefault("event_storming", None)
    session.setdefault("ddd_architecture", None)
    current = session.get("current_question")
    current_questions = session.get("current_questions") or []
    if current is None and current_questions:
        session["current_question"] = current_questions[0]
    if session.get("current_question"):
        session["current_questions"] = [session["current_question"]]
    else:
        session["current_questions"] = []
    use_case_current = session.get("use_case_current_question")
    use_case_current_questions = session.get("use_case_current_questions") or []
    if use_case_current is None and use_case_current_questions:
        session["use_case_current_question"] = use_case_current_questions[0]
    if session.get("use_case_current_question"):
        session["use_case_current_questions"] = [session["use_case_current_question"]]
    else:
        session["use_case_current_questions"] = []
    state = session.get("event_storming")
    if isinstance(state, dict):
        state.setdefault("uc_ids", [])
        state.setdefault("items", {})
        state.setdefault("current_uc", None)
        state.setdefault("completed_count", 0)
        state.setdefault("complete", False)
        state.setdefault("status", "pending")
    ddd_state = session.get("ddd_architecture")
    if isinstance(ddd_state, dict):
        ddd_state.setdefault("uc_ids", [])
        ddd_state.setdefault("items", {})
        ddd_state.setdefault("current_uc", None)
        ddd_state.setdefault("current_step", None)
        ddd_state.setdefault("completed_count", 0)
        ddd_state.setdefault("complete", False)
        ddd_state.setdefault("status", "pending")


def _load_session(root: Path) -> dict[str, Any] | None:
    path = root / SESSION_PATH
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _resume_if_needed(root: Path, session: dict[str, Any]) -> None:
    if session["requirements_gate_passed"]:
        return
    if session.get("current_question") or session.get("current_questions"):
        return
    if session.get("pending_questions"):
        _activate_next_pending_question(session)
        _write_session(root, session)
        return
    try:
        _advance_grill_me(root, session)
    except ValueError as exc:
        session["runtime_error"] = str(exc)
    _write_session(root, session)


def _session_from_requirements_doc(root: Path) -> dict[str, Any] | None:
    path = root / REQUIREMENTS_PATH
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    initial_prompt = _extract_markdown_value(text, "Initial idea")
    if not initial_prompt:
        return None
    clarifications = tuple(_parse_grill_me_rows(text))
    gate_passed = _requirements_gate_passed_from_doc(text)
    use_cases_ready, _ = _validate_runtime_ready_use_case_slices(root)
    session = {
        "initial_prompt": initial_prompt,
        "clarifications": list(clarifications),
        "current_question": None,
        "current_questions": [],
        "pending_questions": [],
        "requirements_gate_passed": gate_passed,
        "active_stage": "requirements",
        "use_cases_ready": use_cases_ready,
        "runtime_error": "",
        "use_case_clarifications": [],
        "use_case_current_question": None,
        "use_case_current_questions": [],
        "use_case_pending_questions": [],
        "event_storming": None,
        "ddd_architecture": None,
    }
    if session["use_cases_ready"]:
        session["active_stage"] = "useCases"
    return session


def _requirements_gate_passed_from_doc(text: str) -> bool:
    if "Current gate: Passed" in text:
        return True
    required_sections = (
        "Business Policy Decisions Needed",
        "Foundational Technology Decisions Needed",
    )
    for heading in required_sections:
        match = re.search(
            rf"^## \d+\. {re.escape(heading)}\s*$([\s\S]*?)(?=^## |\Z)",
            text,
            flags=re.MULTILINE,
        )
        if match is None or not re.search(r"^\s*-\s+None(?:\.|\s|$)", match.group(1), flags=re.MULTILINE):
            return False
    return True


def _extract_markdown_value(text: str, label: str) -> str:
    match = re.search(rf"^- {re.escape(label)}:\s*(.+)$", text, flags=re.MULTILINE)
    return match.group(1).strip() if match else ""


def _parse_grill_me_rows(text: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line in text.splitlines():
        if not line.startswith("| GM-"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        question_text = cells[1]
        answer = cells[2]
        questions = [
            {"question": item, "recommended": ""}
            for item in _split_recovered_questions(question_text)
        ]
        for question in questions:
            rows.append({"questions": [question], "answer": answer})
    return rows


def _split_recovered_questions(text: str) -> list[str]:
    parts = [part.strip() for part in text.split("<br>") if part.strip()]
    if not parts:
        return [text.strip()] if text.strip() else []
    return [re.sub(r"^\d+\.\s*", "", part).strip() for part in parts]


def _normalize_clarification(item: dict[str, Any]) -> dict[str, Any]:
    if "questions" in item and isinstance(item["questions"], list):
        return {
            "questions": [
                {
                    "question": str(question.get("question", "")),
                    "recommended": str(question.get("recommended", "")),
                }
                for question in item["questions"]
            ],
            "answer": str(item.get("answer", "")),
        }
    question = str(item.get("question", "")).strip()
    recommended = str(item.get("recommended", "")).strip()
    return {
        "questions": [{"question": question, "recommended": recommended}]
        if question
        else [],
        "answer": str(item.get("answer", "")),
    }


def _write_session(root: Path, session: dict[str, Any]) -> None:
    path = root / SESSION_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(session, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _result(root: Path, session: dict[str, Any], *, artifact_root: Path | None = None) -> HarvestUiResult:
    documents_root = artifact_root or root
    session_started = bool(session["initial_prompt"])
    requirements_markdown = (
        _read_optional(documents_root / REQUIREMENTS_PATH) if session_started else ""
    )
    use_cases_markdown = (
        _read_optional(documents_root / USE_CASES_PATH)
        if session_started and session.get("use_cases_ready")
        else ""
    )
    gate_passed = bool(session["requirements_gate_passed"])
    event_storming = _event_storming_payload(documents_root, session)
    ddd_architecture = _ddd_architecture_payload(documents_root, session)
    status = "idle" if not session_started else (
        "ddd_architecture_ready" if ddd_architecture.get("complete") else (
        "ddd_architecture_running" if session.get("active_stage") == "dddArchitecture" else (
        "event_storming_ready" if event_storming.get("complete") else (
        "event_storming_running" if session.get("active_stage") == "eventStorming" else (
        "use_cases_ready" if session.get("use_cases_ready") else (
            "requirements_passed" if gate_passed else "requirements_running"
        )))))
    )
    if session_started and not gate_passed:
        current_question = _current_question(session)
    elif session_started and gate_passed and not session.get("use_cases_ready"):
        current_question = _current_use_case_question(session)
    elif session_started and session.get("active_stage") == "eventStorming":
        current_question = _current_event_storming_question(session)
    elif session_started and session.get("active_stage") == "dddArchitecture":
        current_question = _current_ddd_question(session)
    else:
        current_question = None
    current_questions = (current_question,) if current_question else ()
    return HarvestUiResult(
        initial_prompt=session["initial_prompt"],
        status=status,
        active_stage=session["active_stage"],
        requirements_markdown=requirements_markdown,
        use_cases_markdown=use_cases_markdown,
        clarifications=tuple(session["clarifications"]),
        current_question=current_question,
        current_questions=current_questions,
        requirements_gate_passed=gate_passed,
        use_cases_ready=bool(session.get("use_cases_ready")),
        event_storming=event_storming,
        ddd_architecture=ddd_architecture,
        runtime_error=str(session.get("runtime_error", "")),
        workflow=_workflow_projection(),
    )


def _changeset_session_root(root: Path, change_set_id: str) -> Path:
    if not re.fullmatch(r"CHG-[A-Za-z0-9-]+", change_set_id):
        raise ValueError("invalid ChangeSet id")
    return root / CHANGESET_SESSION_ROOT / change_set_id


def _require_active_changeset(root: Path, change_set_id: str) -> None:
    _changeset_session_root(root, change_set_id)
    if not (root / "docs/changes/active" / f"{change_set_id}.md").exists():
        raise ValueError(f"Active ChangeSet does not exist: {change_set_id}.")


def _recover_changeset_session(root: Path, change_set_id: str) -> dict[str, Any]:
    active_ids = sorted(path.stem for path in (root / "docs/changes/active").glob("CHG-*.md"))
    if active_ids != [change_set_id]:
        raise ValueError(f"Resume unavailable for {change_set_id}: no saved workflow state.")
    session = _session_from_requirements_doc(root)
    if session is None:
        raise ValueError(f"Resume unavailable for {change_set_id}: no saved workflow state.")
    _normalize_session(session)
    return session


def _copy_optional_artifact(source: Path, target: Path) -> None:
    if source.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
    elif target.exists():
        target.unlink()


def _copy_optional_tree(source: Path, target: Path, *, replace: bool = True) -> None:
    if replace and target.exists():
        shutil.rmtree(target)
    if source.exists():
        shutil.copytree(source, target, dirs_exist_ok=not replace)


def _copy_scoped_use_case_outputs(root: Path, scoped_root: Path, session: dict[str, Any]) -> None:
    target_root = scoped_root / USE_CASE_SLICE_ROOT
    if target_root.exists():
        shutil.rmtree(target_root)
    uc_ids = _parse_canonical_use_case_ids(_read_optional(root / USE_CASES_PATH))
    event_items = (session.get("event_storming") or {}).get("items", {})
    ddd_items = (session.get("ddd_architecture") or {}).get("items", {})
    for uc_id in uc_ids:
        for name in ("use-case.md", "e2e-goal.md"):
            _copy_optional_artifact(
                root / USE_CASE_SLICE_ROOT / uc_id / name,
                target_root / uc_id / name,
            )
        if event_items.get(uc_id, {}).get("status") == "complete":
            _copy_optional_artifact(
                root / USE_CASE_SLICE_ROOT / uc_id / "event-storming.md",
                target_root / uc_id / "event-storming.md",
            )
        if any(
            step.get("status") == "complete"
            for step in ddd_items.get(uc_id, {}).get("steps", {}).values()
        ):
            _copy_optional_artifact(
                root / USE_CASE_SLICE_ROOT / uc_id / "ddd-design.md",
                target_root / uc_id / "ddd-design.md",
            )


def _normalize_resumed_stage(session: dict[str, Any]) -> None:
    if not session.get("requirements_gate_passed"):
        session["active_stage"] = "requirements"
        session["use_cases_ready"] = False
        return
    if isinstance(session.get("ddd_architecture"), dict):
        session["active_stage"] = "dddArchitecture"
    elif isinstance(session.get("event_storming"), dict):
        session["active_stage"] = "eventStorming"
    elif (
        session.get("use_cases_ready")
        or session.get("use_case_current_question")
        or session.get("use_case_clarifications")
        or session.get("active_stage") == "useCases"
    ):
        session["active_stage"] = "useCases"
    else:
        session["active_stage"] = "requirements"


def _current_question(session: dict[str, Any]) -> dict[str, Any] | None:
    current = session.get("current_question")
    if isinstance(current, dict) and current.get("question"):
        return current
    current_questions = session.get("current_questions") or []
    if current_questions:
        return current_questions[0]
    return None


def _current_use_case_question(session: dict[str, Any]) -> dict[str, Any] | None:
    current = session.get("use_case_current_question")
    if isinstance(current, dict) and current.get("question"):
        return current
    current_questions = session.get("use_case_current_questions") or []
    if current_questions:
        return current_questions[0]
    return None


def _current_event_storming_question(session: dict[str, Any]) -> dict[str, Any] | None:
    state = session.get("event_storming")
    if not isinstance(state, dict):
        return None
    item = state.get("items", {}).get(state.get("current_uc"), {})
    current = item.get("current_question")
    return current if isinstance(current, dict) and current.get("question") else None


def _current_ddd_question(session: dict[str, Any]) -> dict[str, Any] | None:
    state = session.get("ddd_architecture")
    if not isinstance(state, dict):
        return None
    item = state.get("items", {}).get(state.get("current_uc"), {})
    step = item.get("steps", {}).get(state.get("current_step"), {})
    current = step.get("current_question")
    return current if isinstance(current, dict) and current.get("question") else None


def _activate_next_pending_question(session: dict[str, Any]) -> None:
    pending = list(session.get("pending_questions") or [])
    if not pending:
        session["current_question"] = None
        session["current_questions"] = []
        session["pending_questions"] = []
        return
    next_question = pending.pop(0)
    session["current_question"] = next_question
    session["current_questions"] = [next_question]
    session["pending_questions"] = pending


def _activate_next_use_case_pending_question(session: dict[str, Any]) -> None:
    pending = list(session.get("use_case_pending_questions") or [])
    if not pending:
        session["use_case_current_question"] = None
        session["use_case_current_questions"] = []
        session["use_case_pending_questions"] = []
        return
    next_question = pending.pop(0)
    session["use_case_current_question"] = next_question
    session["use_case_current_questions"] = [next_question]
    session["use_case_pending_questions"] = pending


def _advance_grill_me(root: Path, session: dict[str, Any]) -> None:
    result = _run_grill_me(root, session)
    context_markdown = str(result.get("context_markdown", "") or "")
    requirements_markdown = str(result.get("requirements_markdown", "") or "")
    if context_markdown:
        session["draft_context_markdown"] = context_markdown
    if requirements_markdown:
        session["draft_requirements_markdown"] = requirements_markdown
    open_language_questions = _extract_open_language_questions(session["draft_context_markdown"])
    filtered_questions = _filter_new_questions(result["questions"], session)
    if open_language_questions:
        follow_up_questions = filtered_questions or _fallback_open_language_questions(open_language_questions)
        session["requirements_gate_passed"] = False
        session["current_question"] = follow_up_questions[0]
        session["current_questions"] = [follow_up_questions[0]]
        session["pending_questions"] = []
        session["runtime_error"] = ""
        return
    if result["complete"]:
        session["requirements_gate_passed"] = True
        session["current_question"] = None
        session["current_questions"] = []
        session["pending_questions"] = []
    else:
        if not filtered_questions:
            session["requirements_gate_passed"] = True
            session["current_question"] = None
            session["current_questions"] = []
            session["pending_questions"] = []
        else:
            session["requirements_gate_passed"] = False
            session["current_question"] = filtered_questions[0]
            session["current_questions"] = [filtered_questions[0]]
            session["pending_questions"] = []
    session["runtime_error"] = ""


def _advance_use_case_harvest(root: Path, session: dict[str, Any], idea: str) -> None:
    result = _run_use_case_harvest(root, session, idea)
    status = str(result.get("status", "")).strip().lower()
    if status == "complete":
        ready, error = _validate_runtime_ready_use_case_slices(root)
        if not ready:
            raise ValueError(f"use-case harvest reported complete but {error}")
        session["use_cases_ready"] = True
        session["use_case_current_question"] = None
        session["use_case_current_questions"] = []
        session["use_case_pending_questions"] = []
        session["event_storming"] = None
        session["ddd_architecture"] = None
        session["runtime_error"] = ""
        return
    if status == "blocked":
        blocker = str(result.get("blocker", "") or "use-case harvest blocked")
        raise ValueError(blocker)
    questions = _filter_new_use_case_questions(result.get("questions", []), session)
    if not questions:
        blocker = str(result.get("blocker", "") or "use-case harvest needs input but returned no new questions")
        raise ValueError(blocker)
    session["use_cases_ready"] = False
    session["use_case_current_question"] = questions[0]
    session["use_case_current_questions"] = [questions[0]]
    session["use_case_pending_questions"] = questions[1:]
    session["runtime_error"] = ""


def _new_event_storming_state(uc_ids: list[str]) -> dict[str, Any]:
    return {
        "uc_ids": uc_ids,
        "items": {
            uc_id: {
                "status": "pending",
                "current_question": None,
                "clarifications": [],
                "error": "",
            }
            for uc_id in uc_ids
        },
        "current_uc": None,
        "completed_count": 0,
        "complete": False,
        "status": "pending",
    }


def _event_storming_payload(documents_root: Path, session: dict[str, Any]) -> dict[str, Any]:
    state = session.get("event_storming")
    if not isinstance(state, dict):
        return {
            "uc_ids": [],
            "items": {},
            "current_uc": None,
            "completed_count": 0,
            "total_count": 0,
            "complete": False,
            "status": "not_started",
        }
    payload = json.loads(json.dumps(state, ensure_ascii=False))
    payload["total_count"] = len(payload.get("uc_ids", []))
    for uc_id, item in payload.get("items", {}).items():
        item["document_id"] = f"event-storming:{uc_id}"
        if item.get("status") == "complete":
            item["markdown"] = _read_optional(
                documents_root / USE_CASE_SLICE_ROOT / uc_id / "event-storming.md"
            )
    return payload


def _advance_event_storming(
    root: Path,
    session: dict[str, Any],
    change_set_id: str,
    *,
    uc_id: str | None = None,
) -> None:
    state = session["event_storming"]
    target_id = uc_id
    if target_id is None:
        target_id = next(
            (
                item_id
                for item_id in state["uc_ids"]
                if state["items"][item_id]["status"] in {"pending", "error"}
            ),
            None,
        )
    if target_id is None:
        state["complete"] = True
        state["status"] = "complete"
        state["current_uc"] = None
        session["runtime_error"] = ""
        return
    item = state["items"][target_id]
    session["ddd_architecture"] = None
    state["current_uc"] = target_id
    state["status"] = "running"
    item["status"] = "running"
    item["error"] = ""
    output_path = root / USE_CASE_SLICE_ROOT / target_id / "event-storming.md"
    if output_path.exists():
        output_path.unlink()
    try:
        result = _run_event_storming(root, session, change_set_id, target_id)
        status = str(result.get("status", "")).strip().lower()
        if status == "complete":
            ready, error = _validate_event_storming_slice(output_path)
            if not ready:
                raise ValueError(f"event storming reported complete but {error}")
            item["status"] = "complete"
            item["current_question"] = None
            item["error"] = ""
            state["completed_count"] = sum(
                1 for value in state["items"].values() if value.get("status") == "complete"
            )
            state["complete"] = state["completed_count"] == len(state["uc_ids"])
            state["status"] = "complete" if state["complete"] else "running"
            session["runtime_error"] = ""
            return
        if status == "blocked":
            raise ValueError(str(result.get("blocker", "") or "event storming blocked"))
        questions = result.get("questions", [])
        if not isinstance(questions, list) or not questions:
            raise ValueError("event storming needs input but returned no question")
        question = questions[0]
        item["status"] = "needs_input"
        item["current_question"] = {
            "question": str(question.get("question", "")).strip(),
            "recommended": str(question.get("recommended", "") or "").strip(),
        }
        state["status"] = "needs_input"
        session["runtime_error"] = ""
    except ValueError as exc:
        item["status"] = "error"
        item["error"] = str(exc)
        item["current_question"] = None
        state["status"] = "error"
        state["complete"] = False
        session["runtime_error"] = str(exc)


def _validate_event_storming_slice(path: Path) -> tuple[bool, str]:
    if not path.is_file():
        return False, f"missing output: {path}"
    text = path.read_text(encoding="utf-8")
    if _looks_like_placeholder(text):
        return False, f"unverified placeholder in {path}"
    if not re.search(r"^### \[Flow: [^\]]+\]\s*$", text, flags=re.MULTILINE):
        return False, f"no parseable flow in {path}"
    for marker, label in (("🟦", "command"), ("🟧", "event"), ("🟪", "policy")):
        if marker not in text:
            return False, f"missing {label} sticky in {path}"
    return True, ""


def _new_ddd_architecture_state(uc_ids: list[str]) -> dict[str, Any]:
    return {
        "uc_ids": uc_ids,
        "items": {
            uc_id: {
                "status": "pending",
                "impact": {},
                "steps": {
                    step_id: {
                        "label": label,
                        "status": "pending",
                        "current_question": None,
                        "clarifications": [],
                        "error": "",
                    }
                    for step_id, label in DDD_STEPS
                },
            }
            for uc_id in uc_ids
        },
        "current_uc": uc_ids[0] if uc_ids else None,
        "current_step": DDD_STEPS[0][0] if uc_ids else None,
        "completed_count": 0,
        "complete": False,
        "status": "pending",
    }


def _ddd_architecture_payload(documents_root: Path, session: dict[str, Any]) -> dict[str, Any]:
    state = session.get("ddd_architecture")
    if not isinstance(state, dict):
        return {
            "uc_ids": [],
            "items": {},
            "current_uc": None,
            "current_step": None,
            "completed_count": 0,
            "total_count": 0,
            "complete": False,
            "status": "not_started",
            "step_order": [{"id": step_id, "label": label} for step_id, label in DDD_STEPS],
        }
    payload = json.loads(json.dumps(state, ensure_ascii=False))
    payload["total_count"] = len(payload.get("uc_ids", [])) * len(DDD_STEPS)
    payload["step_order"] = [{"id": step_id, "label": label} for step_id, label in DDD_STEPS]
    for uc_id, item in payload.get("items", {}).items():
        if any(step.get("status") == "complete" for step in item.get("steps", {}).values()):
            item["document_id"] = f"ddd-design:{uc_id}"
            item["markdown"] = _read_optional(
                documents_root / USE_CASE_SLICE_ROOT / uc_id / "ddd-design.md"
            )
    return payload


def _advance_ddd_architecture(
    root: Path,
    session: dict[str, Any],
    change_set_id: str,
    *,
    uc_id: str | None = None,
    step_id: str | None = None,
) -> None:
    state = session["ddd_architecture"]
    target_uc = uc_id
    target_step = step_id
    if target_uc is None:
        for candidate_uc in state["uc_ids"]:
            candidate = state["items"][candidate_uc]
            next_step = next(
                (
                    current_id for current_id, _label in DDD_STEPS
                    if candidate["steps"][current_id]["status"] in {"pending", "error", "stale"}
                ),
                None,
            )
            if next_step:
                target_uc, target_step = candidate_uc, next_step
                break
    if target_uc is None or target_step is None:
        state["complete"] = True
        state["status"] = "complete"
        state["current_uc"] = None
        state["current_step"] = None
        session["runtime_error"] = ""
        return
    item = state["items"][target_uc]
    step = item["steps"][target_step]
    state["current_uc"] = target_uc
    state["current_step"] = target_step
    state["status"] = "running"
    item["status"] = "running"
    step["status"] = "running"
    step["error"] = ""
    if target_step == DDD_STEPS[0][0] and not any(
        value.get("status") == "complete" for value in item["steps"].values()
    ):
        for output in (root / USE_CASE_SLICE_ROOT / target_uc / "ddd-design.md", root / "ARCHITECTURE.md"):
            if output.exists():
                output.unlink()
    try:
        result = _run_ddd_architecture(root, session, change_set_id, target_uc, target_step)
        status = str(result.get("status", "")).strip().lower()
        if status == "complete":
            ready, error = _validate_ddd_design_slice(
                root / USE_CASE_SLICE_ROOT / target_uc / "ddd-design.md",
                target_step,
            )
            if not ready:
                raise ValueError(f"DDD architecture reported complete but {error}")
            step["status"] = "complete"
            step["current_question"] = None
            step["error"] = ""
            if result.get("impact"):
                item["impact"] = result["impact"]
            all_done = all(value.get("status") == "complete" for value in item["steps"].values())
            item["status"] = "complete" if all_done else "pending"
            state["completed_count"] = sum(
                1
                for value in state["items"].values()
                for current in value["steps"].values()
                if current.get("status") == "complete"
            )
            state["complete"] = state["completed_count"] == len(state["uc_ids"]) * len(DDD_STEPS)
            state["status"] = "complete" if state["complete"] else "pending"
            session["runtime_error"] = ""
            return
        if status == "blocked":
            raise ValueError(str(result.get("blocker", "") or "DDD architecture blocked"))
        questions = result.get("questions", [])
        if not isinstance(questions, list) or not questions:
            raise ValueError("DDD architecture needs input but returned no question")
        question = questions[0]
        step["status"] = "needs_input"
        step["current_question"] = {
            "question": str(question.get("question", "")).strip(),
            "recommended": str(question.get("recommended", "") or "").strip(),
        }
        item["status"] = "needs_input"
        state["status"] = "needs_input"
        session["runtime_error"] = ""
    except ValueError as exc:
        step["status"] = "error"
        step["error"] = str(exc)
        step["current_question"] = None
        item["status"] = "error"
        state["status"] = "error"
        state["complete"] = False
        session["runtime_error"] = str(exc)


def _validate_ddd_design_slice(path: Path, completed_step: str) -> tuple[bool, str]:
    if not path.is_file():
        return False, f"missing output: {path}"
    text = path.read_text(encoding="utf-8")
    if _looks_like_placeholder(text):
        return False, f"unverified placeholder in {path}"
    required = {
        "entity_vo": ("## Impact Assessment", "## Entity / Value Objects", "Evidence"),
        "behaviors": ("## Behaviors", "Signature", "Policy Evidence"),
        "application_flow": ("## Application Flow", "Signature", "Description", "Application Service"),
        "aggregates": ("## Aggregates", "Aggregate Root", "Atomic"),
        "bounded_contexts": ("## Bounded Contexts", "Communication Type"),
    }
    index = next(index for index, (step_id, _label) in enumerate(DDD_STEPS) if step_id == completed_step)
    terms = tuple(term for step_id, _label in DDD_STEPS[: index + 1] for term in required[step_id])
    missing = [term for term in terms if term not in text]
    if missing:
        return False, f"missing DDD structure in {path}: {', '.join(missing)}"
    if index >= 0 and not _ddd_entity_vo_has_typed_definition(text):
        return False, f"missing typed entity/VO attributes in {path}"
    if completed_step == "bounded_contexts" and not any(
        value in text for value in ("internal_http", "domain_event", "shared_database", "None")
    ):
        return False, f"missing allowed communication type in {path}"
    return True, ""


def _ddd_entity_vo_has_typed_definition(text: str) -> bool:
    section = _ddd_section_text(text, "## Entity / Value Objects")
    typed_columns = {
        "attributes / vos",
        "core attributes",
        "constructor / validation rules",
        "proposed definition",
        "proposed identity / state",
    }
    typed_indexes: list[int] = []
    for line in section.splitlines():
        if not line.startswith("|") or "---" in line:
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        lowered = [cell.lower() for cell in cells]
        if set(lowered) & typed_columns:
            typed_indexes = [index for index, cell in enumerate(lowered) if cell in typed_columns]
            continue
        candidates = [cells[index] for index in typed_indexes if index < len(cells)] if typed_indexes else cells[1:2]
        if any(_looks_like_typed_ddd_value(cell) for cell in candidates):
            return True
    return False


def _looks_like_typed_ddd_value(value: str) -> bool:
    if ":" in value:
        return True
    return bool(re.search(r"`?[A-Z][A-Za-z0-9_<>]*(?:RelativePath|Path|Id|ID|String|Content|Name|List)?`?\s+[a-z][A-Za-z0-9_]*", value))


def _ddd_section_text(text: str, heading: str) -> str:
    start = text.find(heading)
    if start < 0:
        return ""
    next_heading = re.search(r"^##\s+", text[start + len(heading) :], re.MULTILINE)
    if not next_heading:
        return text[start:]
    return text[start : start + len(heading) + next_heading.start()]


def _filter_new_questions(
    questions: list[dict[str, str]],
    session: dict[str, Any],
) -> list[dict[str, str]]:
    seen = _asked_question_keys(session)
    filtered: list[dict[str, str]] = []
    for question in questions:
        text = str(question.get("question", "")).strip()
        if not text:
            continue
        key = _question_key(text)
        if not key or key in seen:
            continue
        seen.add(key)
        filtered.append(question)
    return filtered


def _filter_new_use_case_questions(
    questions: Any,
    session: dict[str, Any],
) -> list[dict[str, str]]:
    if not isinstance(questions, list):
        return []
    seen = _asked_use_case_question_keys(session)
    filtered: list[dict[str, str]] = []
    for item in questions:
        if not isinstance(item, dict):
            continue
        text = str(item.get("question", "")).strip()
        if not text:
            continue
        key = _question_key(text)
        if not key or key in seen:
            continue
        seen.add(key)
        filtered.append(
            {
                "question": text,
                "recommended": str(item.get("recommended", "") or "").strip(),
            }
        )
    return filtered


def _asked_question_keys(session: dict[str, Any]) -> set[str]:
    keys: set[str] = set()
    for item in session.get("clarifications", []):
        for question in item.get("questions") or []:
            key = _question_key(str(question.get("question", "")))
            if key:
                keys.add(key)
    for question in session.get("pending_questions") or []:
        key = _question_key(str(question.get("question", "")))
        if key:
            keys.add(key)
    current = _current_question(session)
    if current:
        key = _question_key(str(current.get("question", "")))
        if key:
            keys.add(key)
    return keys


def _asked_use_case_question_keys(session: dict[str, Any]) -> set[str]:
    keys: set[str] = set()
    for item in session.get("use_case_clarifications", []):
        for question in item.get("questions") or []:
            key = _question_key(str(question.get("question", "")))
            if key:
                keys.add(key)
    for question in session.get("use_case_pending_questions") or []:
        key = _question_key(str(question.get("question", "")))
        if key:
            keys.add(key)
    current = _current_use_case_question(session)
    if current:
        key = _question_key(str(current.get("question", "")))
        if key:
            keys.add(key)
    return keys


def _question_key(text: str) -> str:
    normalized = re.sub(r"[^0-9a-zA-Z가-힣]+", "", text).lower()
    stop_words = (
        "무엇인가요",
        "무엇입니까",
        "무엇인지",
        "어떤",
        "알려주세요",
        "확인해주세요",
        "해주세요",
        "인가요",
        "입니까",
        "please",
        "what",
        "which",
        "tell",
        "about",
        "the",
        "a",
        "an",
    )
    for word in stop_words:
        normalized = normalized.replace(word, "")
    return normalized[:120]


def _run_grill_me(root: Path, session: dict[str, Any]) -> dict[str, Any]:
    grill_me_skill_path = root / GRILL_ME_SKILL_PATH
    requirements_skill_path = root / REQUIREMENTS_SKILL_PATH
    if not grill_me_skill_path.exists():
        raise ValueError(f"missing required Grill-Me skill: {GRILL_ME_SKILL_PATH}")
    if not requirements_skill_path.exists():
        raise ValueError(f"missing required requirements skill: {REQUIREMENTS_SKILL_PATH}")

    run_dir = root / ".harness/ui/grill-me-runs" / uuid4().hex[:12]
    run_dir.mkdir(parents=True, exist_ok=True)
    turn_result = _run_grill_me_question_turn(root, session, run_dir)
    if not turn_result["complete"]:
        return {
            "complete": False,
            "questions": turn_result["questions"],
            "requirements_markdown": "",
            "context_markdown": "",
        }
    return _run_grill_me_finalizer(root, session, requirements_skill_path, run_dir)


def _run_use_case_harvest(root: Path, session: dict[str, Any], idea: str) -> dict[str, Any]:
    agent_config_path = root / USE_CASE_AGENT_CONFIG_PATH
    skill_path = root / USE_CASE_SKILL_PATH
    if not agent_config_path.exists():
        raise ValueError(f"missing use-case agent config: {USE_CASE_AGENT_CONFIG_PATH}")
    if not skill_path.exists():
        raise ValueError(f"missing use-case skill config: {USE_CASE_SKILL_PATH}")
    with agent_config_path.open("rb") as file:
        agent_config = tomllib.load(file)

    run_id = f"interactive-use-cases-{uuid4().hex[:12]}"
    run_dir = root / ".harness/ui/use-case-runs" / run_id
    step_dir = run_dir / "step"
    step_dir.mkdir(parents=True, exist_ok=True)
    final_message_path = step_dir / "final-message.md"
    prompt_path = step_dir / "prompt.md"
    command_path = step_dir / "command.json"
    step = Step(
        id="harvest-use-cases",
        kind=StepKind.AGENT,
        name="Derive runtime-ready use case docs",
        agent_id="harness_usecases",
        skill_id="harness-usecases",
        inputs=(CONTEXT_PATH, REQUIREMENTS_PATH),
        outputs=(USE_CASES_PATH, USE_CASE_SLICE_ROOT),
        timeout_sec=USE_CASE_DEFINITION_TIMEOUT_SEC,
        metadata={
            "stage": "harvest",
            "scope": "runtime_ready_use_cases",
            "interactive": True,
            "slice_outputs": {
                "root": str(USE_CASE_SLICE_ROOT),
                "required_per_use_case": ("use-case.md", "e2e-goal.md"),
            },
        },
    )
    context = RunContext(
        run_id=run_id,
        workflow_name="harvest-workflow",
        mode=RunMode.APPLY,
        repo_root=root,
        workdir=root,
        run_dir=run_dir,
        metadata={
            "stage": "interactive_harvest",
            "initial_idea": idea or session.get("initial_prompt", ""),
            "interactive_turn": "use_cases",
        },
    )
    prompt = build_agent_prompt(
        step=step,
        context=context,
        agent_config=agent_config,
        agent_config_path=USE_CASE_AGENT_CONFIG_PATH,
        skill_path=skill_path,
        skill_body=skill_path.read_text(encoding="utf-8"),
    )
    prompt = f"{prompt}\n\n{_use_case_turn_contract(session)}"
    prompt_path.write_text(prompt, encoding="utf-8")
    command = [
        "codex",
        "exec",
        "--cd",
        str(root),
        "--skip-git-repo-check",
        "-c",
        'approval_policy="never"',
        "--sandbox",
        "workspace-write",
        "--output-last-message",
        str(final_message_path),
    ]
    model = agent_config.get("model")
    if isinstance(model, str) and model:
        command.extend(["--model", model])
    reasoning_effort = agent_config.get("model_reasoning_effort")
    if isinstance(reasoning_effort, str) and reasoning_effort:
        command.extend(["-c", f'model_reasoning_effort="{reasoning_effort}"'])
    command.append("-")
    command_path.write_text(json.dumps(command, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    try:
        completed = subprocess.run(
            command,
            cwd=root,
            input=prompt,
            text=True,
            capture_output=True,
            timeout=USE_CASE_DEFINITION_TIMEOUT_SEC,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise ValueError(
            f"use-case definition timed out after {USE_CASE_DEFINITION_TIMEOUT_SEC} seconds. "
            "Retry to continue from this stage."
        ) from exc
    (step_dir / "stdout.txt").write_text(completed.stdout, encoding="utf-8")
    (step_dir / "stderr.txt").write_text(completed.stderr, encoding="utf-8")
    if completed.returncode != 0:
        error = completed.stderr.strip() or completed.stdout.strip()
        raise ValueError(f"use-case harvest execution failed: {error}")
    final_message = final_message_path.read_text(encoding="utf-8")
    return _parse_use_case_harvest_json(final_message)


def _run_event_storming(
    root: Path,
    session: dict[str, Any],
    change_set_id: str,
    uc_id: str,
) -> dict[str, Any]:
    agent_config_path = root / EVENT_STORMING_AGENT_CONFIG_PATH
    skill_path = root / EVENT_STORMING_SKILL_PATH
    if not agent_config_path.exists():
        raise ValueError(f"missing event-storming agent config: {EVENT_STORMING_AGENT_CONFIG_PATH}")
    if not skill_path.exists():
        raise ValueError(f"missing event-storming skill config: {EVENT_STORMING_SKILL_PATH}")
    with agent_config_path.open("rb") as file:
        agent_config = tomllib.load(file)

    run_id = f"interactive-event-storming-{uuid4().hex[:12]}"
    run_dir = root / ".harness/ui/event-storming-runs" / run_id
    step_dir = run_dir / "step"
    step_dir.mkdir(parents=True, exist_ok=True)
    final_message_path = step_dir / "final-message.md"
    prompt_path = step_dir / "prompt.md"
    command_path = step_dir / "command.json"
    output_path = USE_CASE_SLICE_ROOT / uc_id / "event-storming.md"
    step = Step(
        id=f"event-storming-{uc_id}",
        kind=StepKind.AGENT,
        name=f"Derive event storming for {uc_id}",
        agent_id="oracle",
        skill_id="harness-event-storming",
        inputs=(
            Path("docs/changes/active") / f"{change_set_id}.md",
            USE_CASE_SLICE_ROOT / uc_id / "use-case.md",
            USE_CASE_SLICE_ROOT / uc_id / "e2e-goal.md",
        ),
        outputs=(output_path,),
        timeout_sec=EVENT_STORMING_TIMEOUT_SEC,
        metadata={"stage": "event-storming", "scope": uc_id, "interactive": True},
    )
    context = RunContext(
        run_id=run_id,
        workflow_name="event-storming-workflow",
        mode=RunMode.APPLY,
        repo_root=root,
        workdir=root,
        run_dir=run_dir,
        metadata={"stage": "event_storming", "change_set_id": change_set_id, "uc_id": uc_id},
    )
    prompt = build_agent_prompt(
        step=step,
        context=context,
        agent_config=agent_config,
        agent_config_path=EVENT_STORMING_AGENT_CONFIG_PATH,
        skill_path=skill_path,
        skill_body=skill_path.read_text(encoding="utf-8"),
    )
    item = session.get("event_storming", {}).get("items", {}).get(uc_id, {})
    prompt = f"{prompt}\n\n{_event_storming_turn_contract(change_set_id, uc_id, item)}"
    prompt_path.write_text(prompt, encoding="utf-8")
    command = [
        "codex",
        "exec",
        "--cd",
        str(root),
        "--skip-git-repo-check",
        "-c",
        'approval_policy="never"',
        "--sandbox",
        "workspace-write",
        "--output-last-message",
        str(final_message_path),
    ]
    model = agent_config.get("model")
    if isinstance(model, str) and model:
        command.extend(["--model", model])
    reasoning_effort = agent_config.get("model_reasoning_effort")
    if isinstance(reasoning_effort, str) and reasoning_effort:
        command.extend(["-c", f'model_reasoning_effort="{reasoning_effort}"'])
    command.append("-")
    command_path.write_text(json.dumps(command, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    try:
        completed = subprocess.run(
            command,
            cwd=root,
            input=prompt,
            text=True,
            capture_output=True,
            timeout=EVENT_STORMING_TIMEOUT_SEC,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise ValueError(
            f"event storming timed out after {EVENT_STORMING_TIMEOUT_SEC} seconds. "
            "Retry to continue from this use case."
        ) from exc
    (step_dir / "stdout.txt").write_text(completed.stdout, encoding="utf-8")
    (step_dir / "stderr.txt").write_text(completed.stderr, encoding="utf-8")
    if completed.returncode != 0:
        error = completed.stderr.strip() or completed.stdout.strip()
        raise ValueError(f"event-storming execution failed: {error}")
    return _parse_event_storming_json(final_message_path.read_text(encoding="utf-8"))


def _event_storming_turn_contract(
    change_set_id: str,
    uc_id: str,
    item: dict[str, Any],
) -> str:
    return f"""## Interactive Event Storming Turn

Target ChangeSet: {change_set_id}
Target Use Case: {uc_id}

Return only JSON with keys: status, questions, changed_files, blocker.
- Return `needs_input` with exactly one question object when one business-policy answer is required.
- Return `complete` only after writing `docs/use-cases/{uc_id}/event-storming.md` with validated commands, events, policies, systems, external systems, and invariants.
- Return `blocked` only when existing inputs cannot be corrected by one user answer in this stage.
- Model only `{uc_id}`; use its goal or first actor action as initial command.

Event-storming answer history:
{json.dumps(item.get("clarifications", []), ensure_ascii=False, indent=2)}
"""


def _parse_event_storming_json(text: str) -> dict[str, Any]:
    stripped = text.strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", stripped, flags=re.DOTALL)
        if match is None:
            raise ValueError(f"event storming returned non-JSON output: {stripped}")
        data = json.loads(match.group(0))
    status = str(data.get("status", "") or "").strip().lower()
    if status not in {"needs_input", "complete", "blocked"}:
        raise ValueError(f"event storming returned invalid status: {status or '<empty>'}")
    questions = data.get("questions", [])
    if not isinstance(questions, list):
        raise ValueError("event storming returned invalid questions")
    return {
        "status": status,
        "questions": questions,
        "changed_files": [str(item) for item in data.get("changed_files", [])],
        "blocker": str(data.get("blocker", "") or ""),
    }


def _run_ddd_architecture(
    root: Path,
    session: dict[str, Any],
    change_set_id: str,
    uc_id: str,
    step_id: str,
) -> dict[str, Any]:
    agent_config_path = root / DDD_AGENT_CONFIG_PATH
    skill_path = root / DDD_SKILL_PATH
    if not agent_config_path.exists():
        raise ValueError(f"missing DDD agent config: {DDD_AGENT_CONFIG_PATH}")
    if not skill_path.exists():
        raise ValueError(f"missing DDD skill config: {DDD_SKILL_PATH}")
    with agent_config_path.open("rb") as file:
        agent_config = tomllib.load(file)
    run_id = f"interactive-ddd-{uuid4().hex[:12]}"
    run_dir = root / ".harness/ui/ddd-runs" / run_id
    step_dir = run_dir / "step"
    step_dir.mkdir(parents=True, exist_ok=True)
    final_message_path = step_dir / "final-message.md"
    output_path = USE_CASE_SLICE_ROOT / uc_id / "ddd-design.md"
    step = Step(
        id=f"ddd-{uc_id}-{step_id}",
        kind=StepKind.AGENT,
        name=f"Derive DDD {step_id} for {uc_id}",
        agent_id="ddd_architect",
        skill_id="harness-ddd-design",
        inputs=(
            Path("docs/changes/active") / f"{change_set_id}.md",
            USE_CASE_SLICE_ROOT / uc_id / "use-case.md",
            USE_CASE_SLICE_ROOT / uc_id / "event-storming.md",
            USE_CASE_SLICE_ROOT / uc_id / "e2e-goal.md",
        ),
        outputs=(output_path, Path("ARCHITECTURE.md")),
        timeout_sec=DDD_TIMEOUT_SEC,
        metadata={"stage": "ddd-architecture", "scope": uc_id, "substep": step_id, "interactive": True},
    )
    context = RunContext(
        run_id=run_id,
        workflow_name="ddd-architecture-workflow",
        mode=RunMode.APPLY,
        repo_root=root,
        workdir=root,
        run_dir=run_dir,
        metadata={"stage": "ddd_architecture", "change_set_id": change_set_id, "uc_id": uc_id, "substep": step_id},
    )
    prompt = build_agent_prompt(
        step=step,
        context=context,
        agent_config=agent_config,
        agent_config_path=DDD_AGENT_CONFIG_PATH,
        skill_path=skill_path,
        skill_body=skill_path.read_text(encoding="utf-8"),
    )
    item = session["ddd_architecture"]["items"][uc_id]
    prompt = f"{prompt}\n\n{_ddd_turn_contract(change_set_id, uc_id, step_id, item)}"
    (step_dir / "prompt.md").write_text(prompt, encoding="utf-8")
    command = [
        "codex", "exec", "--cd", str(root), "--skip-git-repo-check",
        "-c", 'approval_policy="never"', "--sandbox", "workspace-write",
        "--output-last-message", str(final_message_path),
    ]
    model = agent_config.get("model")
    if isinstance(model, str) and model:
        command.extend(["--model", model])
    effort = agent_config.get("model_reasoning_effort")
    if isinstance(effort, str) and effort:
        command.extend(["-c", f'model_reasoning_effort="{effort}"'])
    command.append("-")
    (step_dir / "command.json").write_text(json.dumps(command, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    try:
        completed = subprocess.run(
            command, cwd=root, input=prompt, text=True, capture_output=True,
            timeout=DDD_TIMEOUT_SEC, check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise ValueError(
            f"DDD architecture timed out after {DDD_TIMEOUT_SEC} seconds. "
            "Retry to continue from this substep."
        ) from exc
    (step_dir / "stdout.txt").write_text(completed.stdout, encoding="utf-8")
    (step_dir / "stderr.txt").write_text(completed.stderr, encoding="utf-8")
    if completed.returncode != 0:
        error = completed.stderr.strip() or completed.stdout.strip()
        raise ValueError(f"DDD architecture execution failed: {error}")
    return _parse_ddd_json(final_message_path.read_text(encoding="utf-8"))


def _ddd_turn_contract(change_set_id: str, uc_id: str, step_id: str, item: dict[str, Any]) -> str:
    return f"""## Interactive Phased DDD Architecture Turn

Target ChangeSet: {change_set_id}
Target Use Case: {uc_id}
Target Substep: {step_id}

Execute exactly this substep. Do not implement code or advance to another substep.
Update `docs/use-cases/{uc_id}/ddd-design.md` as one evolving document. Preserve prior completed sections.
For `bounded_contexts`, also update `ARCHITECTURE.md` with approved boundary constraints.
Return only JSON with keys: status, questions, changed_files, blocker, impact.
- `needs_input`: exactly one modeling question.
- `complete`: current substep sections written with event-storming evidence.
- `blocked`: inputs cannot be corrected by one DDD answer.

Substep requirements:
- `entity_vo`: write `## Impact Assessment` with exact columns `Element Type | Element | Status | Baseline Evidence | Event Storming Evidence`; write `## Entity / Value Objects` with exact columns `Entity | Attributes / VOs | Status | Previous Definition | Proposed Definition | Evidence`; classify new/modify/reuse using completed design docs and `ARCHITECTURE.md` first, read-only implementation fallback; include typed attributes/VO fields such as `notePath: WorkspaceRelativePath (required, evidence)` and `WorkspaceRelativePath {{ value: String }} (normalized inside workspace)`.
- `behaviors`: write `## Behaviors`; include entity/domain-service `Signature` and `Policy Evidence`.
- `application_flow`: write `## Application Flow` with exact columns `Application Service | Signature | Description | Calls | Evidence`; include the application service signature and a short prose description of logic flow; do not write pseudocode.
- `aggregates`: write `## Aggregates`; choose explicit aggregate names; include `Aggregate Root`, contained models, `Atomic` invariant evidence.
- `bounded_contexts`: write `## Bounded Contexts`; include `Communication Type` using only `internal_http`, `domain_event`, or `shared_database`; internal HTTP is a public client/API boundary, never internal-model access.

Additional user prompts for rerun:
{json.dumps(item.get("steps", {}).get(step_id, {}).get("rerun_prompts", []), ensure_ascii=False, indent=2)}

Prior step state:
{json.dumps(item, ensure_ascii=False, indent=2)}
"""


def _parse_ddd_json(text: str) -> dict[str, Any]:
    stripped = text.strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", stripped, flags=re.DOTALL)
        if match is None:
            raise ValueError(f"DDD architecture returned non-JSON output: {stripped}")
        data = json.loads(match.group(0))
    status = str(data.get("status", "") or "").strip().lower()
    if status not in {"needs_input", "complete", "blocked"}:
        raise ValueError(f"DDD architecture returned invalid status: {status or '<empty>'}")
    questions = data.get("questions", [])
    if not isinstance(questions, list):
        raise ValueError("DDD architecture returned invalid questions")
    impact = data.get("impact", {})
    return {
        "status": status,
        "questions": questions,
        "changed_files": [str(item) for item in data.get("changed_files", [])],
        "blocker": str(data.get("blocker", "") or ""),
        "impact": impact if isinstance(impact, dict) else {},
    }


def _use_case_turn_contract(session: dict[str, Any]) -> str:
    return f"""## 10. Interactive Use-Case Harvest Turn

Return only JSON with keys: status, questions, changed_files, blocker.

Status rules:
- Return status `needs_input` when one focused user answer is required before use-case docs can be correct.
- Return status `complete` only after writing docs/design/유스케이스.md and every required docs/use-cases/<UC-ID>/use-case.md and docs/use-cases/<UC-ID>/e2e-goal.md file.
- Return status `blocked` only when the existing requirements/context inputs are not ready and no user answer in this stage can resolve it.

Question rules:
- When status is `needs_input`, include exactly one question object with keys question and recommended.
- Ask only the single highest-priority blocker for this turn.
- Do not queue non-blocking follow-up questions.
- Do not ask any question already present in Use-case answer history.
- If the answer history resolves enough ambiguity, write the use-case docs and return status `complete`.

Use-case answer history:
{json.dumps(session.get("use_case_clarifications", []), ensure_ascii=False, indent=2)}
"""


def _parse_use_case_harvest_json(text: str) -> dict[str, Any]:
    stripped = text.strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", stripped, flags=re.DOTALL)
        if match is None:
            raise ValueError(f"use-case harvest returned non-JSON output: {stripped}")
        data = json.loads(match.group(0))
    status = str(data.get("status", "") or "").strip().lower()
    if status not in {"needs_input", "complete", "blocked"}:
        raise ValueError(f"use-case harvest returned invalid status: {status or '<empty>'}")
    questions = data.get("questions", [])
    if not isinstance(questions, list):
        raise ValueError("use-case harvest returned invalid questions")
    changed_files = data.get("changed_files", [])
    if not isinstance(changed_files, list):
        raise ValueError("use-case harvest returned invalid changed_files")
    return {
        "status": status,
        "questions": questions,
        "changed_files": [str(item) for item in changed_files],
        "blocker": str(data.get("blocker", "") or ""),
    }


def _run_grill_me_question_turn(root: Path, session: dict[str, Any], run_dir: Path) -> dict[str, Any]:
    step_dir = run_dir / "question-turn"
    step_dir.mkdir(parents=True, exist_ok=True)
    prompt = _grill_me_prompt(session)
    final_message = _exec_codex_prompt(root, step_dir, prompt, "Grill-Me question turn")
    return _parse_grill_me_turn_json(final_message)


def _run_grill_me_finalizer(
    root: Path,
    session: dict[str, Any],
    requirements_skill_path: Path,
    run_dir: Path,
) -> dict[str, Any]:
    step_dir = run_dir / "finalize"
    step_dir.mkdir(parents=True, exist_ok=True)
    prompt = _grill_me_finalization_prompt(session, requirements_skill_path.read_text(encoding="utf-8"))
    final_message = _exec_codex_prompt(root, step_dir, prompt, "Grill-Me finalization")
    result = _parse_grill_me_json(final_message)
    if not result["requirements_markdown"] or not result["context_markdown"]:
        if result["complete"] and not result["questions"] and _is_legacy_grill_me_result(final_message):
            return {"complete": True, "questions": []}
        raise ValueError("Grill-Me finalization returned incomplete draft documents")
    return result


def _is_legacy_grill_me_result(text: str) -> bool:
    try:
        data = json.loads(text.strip())
    except json.JSONDecodeError:
        return False
    if not isinstance(data, dict):
        return False
    return set(data.keys()).issubset({"complete", "questions", "question", "recommended"})


def _exec_codex_prompt(root: Path, step_dir: Path, prompt: str, label: str) -> str:
    final_message_path = step_dir / "final-message.md"
    prompt_path = step_dir / "prompt.md"
    prompt_path.write_text(prompt, encoding="utf-8")
    command = [
        "codex",
        "exec",
        "--cd",
        str(root),
        "--skip-git-repo-check",
        "-c",
        'approval_policy="never"',
        "--sandbox",
        "workspace-write",
        "--output-last-message",
        str(final_message_path),
        "-",
    ]
    completed = subprocess.run(
        command,
        cwd=root,
        input=prompt,
        text=True,
        capture_output=True,
        timeout=300,
        check=False,
    )
    (step_dir / "stdout.txt").write_text(completed.stdout, encoding="utf-8")
    (step_dir / "stderr.txt").write_text(completed.stderr, encoding="utf-8")
    if completed.returncode != 0:
        error = completed.stderr.strip() or completed.stdout.strip()
        raise ValueError(f"{label} failed: {error}")
    return final_message_path.read_text(encoding="utf-8")


def _grill_me_prompt(session: dict[str, Any]) -> str:
    return f"""Use $grill-me to clarify requirements.

Return only JSON with keys: complete, questions.
When incomplete, return exactly 1 question in questions[].
Each question object must have keys: question, recommended.

Question rules:
- Ask exactly one focused question at a time.
- Keep the loop scoped to one MVP and one use-case-sized ChangeSet.
- Do not ask any question already present in Compact Q/A history.
- Do not ask semantically equivalent questions to prior or active questions.
- If a previous answer is partial, ask only for the missing detail.
- Generate questions only from unresolved decisions.
- Ask only the single highest-priority blocker.
- Do not queue non-blocking follow-up questions.
- Return complete=true once the confirmed decisions are sufficient for a separate writer step to draft context.md and docs/design/요구사항.md.

Initial prompt:
{session["initial_prompt"]}

Compact Q/A history:
{json.dumps(_question_turn_history(session), ensure_ascii=False, indent=2)}
"""


def _grill_me_finalization_prompt(session: dict[str, Any], requirements_skill: str) -> str:
    return f"""Use the confirmed requirement decisions below to draft the final harvest documents.

Return only JSON with keys: complete, questions, requirements_markdown, context_markdown.
Always include draft requirements_markdown and context_markdown that reflect the current confirmed state.
When incomplete, return exactly 1 question in questions[].
Each question object must have keys: question, recommended.

Document rules:
- In requirements_markdown, never use a clarification table column named `Answer`; use `Response`.
- context_markdown must follow the root context.md structure from harness-requirements and include the Ubiquitous Language table.
- requirements_markdown must use canonical terms from context_markdown.
- Return complete=true only when context_markdown has no unresolved entries under `## 3. Open Language Questions`.
- If context_markdown still has any open language question, return complete=false and ask the focused follow-up question that resolves it.

Initial prompt:
{session["initial_prompt"]}

Compact Q/A history:
{json.dumps(_question_turn_history(session), ensure_ascii=False, indent=2)}

Harness requirements standards:
{requirements_skill}
"""


def _asked_questions(session: dict[str, Any]) -> list[dict[str, str]]:
    questions: list[dict[str, str]] = []
    for item in session.get("clarifications", []):
        answer = str(item.get("answer", ""))
        for question in item.get("questions") or []:
            questions.append(
                {
                    "question": str(question.get("question", "")),
                    "answer": answer,
                    "recommended": str(question.get("recommended", "")),
                    "status": "answered",
                }
            )
    return questions


def _question_turn_history(session: dict[str, Any]) -> list[dict[str, str]]:
    history = _asked_questions(session)
    current = _current_question(session)
    if current and str(current.get("question", "")).strip():
        history.append(
            {
                "question": str(current.get("question", "")),
                "answer": "",
                "recommended": str(current.get("recommended", "")),
                "status": "active",
            }
        )
    return history


def _parse_grill_me_turn_json(text: str) -> dict[str, Any]:
    stripped = text.strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", stripped, flags=re.DOTALL)
        if match is None:
            raise ValueError(f"Grill-Me returned non-JSON output: {stripped}")
        data = json.loads(match.group(0))
    complete = bool(data.get("complete"))
    raw_questions = data.get("questions", [])
    if not isinstance(raw_questions, list):
        raise ValueError("Grill-Me returned invalid questions")
    questions = []
    for item in raw_questions[:1]:
        if not isinstance(item, dict):
            continue
        question = str(item.get("question", "")).strip()
        recommended = str(item.get("recommended", "")).strip()
        if question:
            questions.append({"question": question, "recommended": recommended})
    if not complete and not questions:
        legacy_question = str(data.get("question", "")).strip()
        legacy_recommended = str(data.get("recommended", "")).strip()
        if legacy_question:
            questions.append({"question": legacy_question, "recommended": legacy_recommended})
    return {"complete": complete, "questions": questions}


def _parse_grill_me_json(text: str) -> dict[str, Any]:
    stripped = text.strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", stripped, flags=re.DOTALL)
        if match is None:
            raise ValueError(f"Grill-Me returned non-JSON output: {stripped}")
        data = json.loads(match.group(0))
    complete = bool(data.get("complete"))
    requirements_markdown = str(data.get("requirements_markdown", "") or "").strip()
    context_markdown = str(data.get("context_markdown", "") or "").strip()
    raw_questions = data.get("questions", [])
    if not isinstance(raw_questions, list):
        raise ValueError("Grill-Me returned invalid questions")
    questions = []
    for item in raw_questions[:1]:
        if not isinstance(item, dict):
            continue
        question = str(item.get("question", "")).strip()
        recommended = str(item.get("recommended", "")).strip()
        if question:
            questions.append({"question": question, "recommended": recommended})
    if not complete and not questions:
        legacy_question = str(data.get("question", "")).strip()
        legacy_recommended = str(data.get("recommended", "")).strip()
        if legacy_question:
            questions.append({"question": legacy_question, "recommended": legacy_recommended})
    return {
        "complete": complete,
        "questions": questions,
        "requirements_markdown": requirements_markdown,
        "context_markdown": context_markdown,
    }


def _extract_open_language_questions(markdown: str) -> list[str]:
    if not markdown.strip():
        return []
    match = re.search(
        r"^## 3\. Open Language Questions\s*$([\s\S]*?)(?=^##\s|\Z)",
        markdown,
        flags=re.MULTILINE,
    )
    if match is None:
        return []
    questions: list[str] = []
    for line in match.group(1).splitlines():
        stripped = line.strip()
        if not stripped.startswith("- "):
            continue
        question = stripped[2:].strip()
        if not question:
            continue
        if question.lower() in {"none", "none."}:
            continue
        questions.append(question)
    return questions


def _fallback_open_language_questions(open_questions: list[str]) -> list[dict[str, str]]:
    return [
        {
            "question": question,
            "recommended": "Confirm the canonical term or naming decision explicitly based on the current context draft.",
        }
        for question in open_questions[:3]
    ]


def _write_context_doc(root: Path, session: dict[str, Any]) -> None:
    path = root / CONTEXT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    markdown = str(session.get("draft_context_markdown", "") or "").strip()
    if markdown:
        path.write_text(markdown + "\n", encoding="utf-8")
        return
    path.write_text(_fallback_context_markdown(session) + "\n", encoding="utf-8")


def _write_requirements_doc(root: Path, session: dict[str, Any]) -> None:
    path = root / REQUIREMENTS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    markdown = _sanitize_requirements_markdown(
        str(session.get("draft_requirements_markdown", "") or "").strip()
    )
    if markdown:
        path.write_text(markdown + "\n", encoding="utf-8")
        return
    gate = "Passed" if session["requirements_gate_passed"] else "Needs Clarification"
    lines = [
        "# 요구사항",
        "",
        f"- Initial idea: {session['initial_prompt']}",
        f"- Current gate: {gate}",
        "",
        "## Grill-Me Clarifications",
        "",
        "| ID | Question | Response |",
        "| --- | --- | --- |",
    ]
    for index, item in enumerate(session["clarifications"], start=1):
        questions = item.get("questions") or []
        question_text = questions[0].get("question", "") if questions else ""
        lines.append(f"| GM-{index:03d} | {question_text} | {item.get('answer', '')} |")
    if _current_question(session) or session.get("pending_questions"):
        lines.extend(["", "## Blocking Open Language Questions", ""])
        queue = []
        current = _current_question(session)
        if current:
            queue.append(current)
        queue.extend(session.get("pending_questions") or [])
        for index, item in enumerate(queue, start=1):
            recommended = item.get("recommended", "")
            suffix = f" Recommended: {recommended}" if recommended else ""
            lines.append(f"- Q{index}: {item.get('question', '')}{suffix}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _sanitize_requirements_markdown(markdown: str) -> str:
    if not markdown:
        return ""
    return markdown.replace("| ID | Question | Answer |", "| ID | Question | Response |")


def _fallback_context_markdown(session: dict[str, Any]) -> str:
    open_questions: list[str] = []
    current = _current_question(session)
    if current and current.get("question"):
        open_questions.append(str(current["question"]))
    for item in session.get("pending_questions") or []:
        question = str(item.get("question", "")).strip()
        if question:
            open_questions.append(question)
    lines = [
        "# Project Context",
        "",
        "## 1. Ubiquitous Language",
        "",
        "| Canonical Term | Korean | English | Type | Definition | Aliases | Forbidden Terms | Source |",
        "|---|---|---|---|---|---|---|---|",
        "| User | 사용자 | User | Actor | Primary external actor confirmed through harvest. | - | - | grill-me |",
        "",
        "## 2. Naming Rules",
        "",
        "- Documents must use `Canonical Term`.",
        "- Code class, method, package, command, event, and policy identifiers must use `English`.",
        "- User-facing text should use `Korean`.",
        "- `Forbidden Terms` must not be used in new documents, plans, tests, or code identifiers.",
        "- Aliases are recorded only for migration/search context and must not be introduced as new canonical language.",
        "",
        "## 3. Blocking Open Language Questions",
        "",
    ]
    if open_questions:
        lines.extend(f"- {question}" for question in open_questions)
    else:
        lines.append("- None.")
    lines.extend(["", "## 4. Deferred Language Questions", "", "- None."])
    return "\n".join(lines)


def _has_runtime_ready_use_case_slices(root: Path) -> bool:
    ready, _ = _validate_runtime_ready_use_case_slices(root)
    return ready


def _sync_use_case_readiness(root: Path, session: dict[str, Any]) -> None:
    if not session.get("requirements_gate_passed"):
        session["use_cases_ready"] = False
        return
    ready, _ = _validate_runtime_ready_use_case_slices(root)
    was_ready = bool(session.get("use_cases_ready"))
    session["use_cases_ready"] = ready
    if ready and isinstance(session.get("ddd_architecture"), dict):
        session["active_stage"] = "dddArchitecture"
    elif ready and isinstance(session.get("event_storming"), dict):
        session["active_stage"] = "eventStorming"
    elif ready:
        session["active_stage"] = "useCases"
    elif was_ready:
        session["active_stage"] = "requirements"


def _validate_runtime_ready_use_case_slices(root: Path) -> tuple[bool, str]:
    canonical_path = root / USE_CASES_PATH
    if not canonical_path.is_file():
        return False, (
            "docs/design/유스케이스.md is missing, empty, or has no parseable UC entries. "
            "Expected '- UC-001. ...' or '## UC-001. ...'."
        )

    canonical_text = canonical_path.read_text(encoding="utf-8")
    if not canonical_text.strip():
        return False, (
            "docs/design/유스케이스.md is missing, empty, or has no parseable UC entries. "
            "Expected '- UC-001. ...' or '## UC-001. ...'."
        )

    uc_ids = _parse_canonical_use_case_ids(canonical_text)
    if not uc_ids:
        return False, (
            "docs/design/유스케이스.md is missing, empty, or has no parseable UC entries. "
            "Expected '- UC-001. ...' or '## UC-001. ...'."
        )

    missing_files: list[str] = []
    for uc_id in uc_ids:
        use_case_path = root / USE_CASE_SLICE_ROOT / uc_id / "use-case.md"
        e2e_path = root / USE_CASE_SLICE_ROOT / uc_id / "e2e-goal.md"
        if not use_case_path.is_file():
            missing_files.append(str(USE_CASE_SLICE_ROOT / uc_id / "use-case.md"))
        if not e2e_path.is_file():
            missing_files.append(str(USE_CASE_SLICE_ROOT / uc_id / "e2e-goal.md"))
        if missing_files:
            continue
        if _looks_like_placeholder(use_case_path.read_text(encoding="utf-8")):
            missing_files.append(str(USE_CASE_SLICE_ROOT / uc_id / "use-case.md"))
        if _looks_like_placeholder(e2e_path.read_text(encoding="utf-8")):
            missing_files.append(str(USE_CASE_SLICE_ROOT / uc_id / "e2e-goal.md"))
    if missing_files:
        missing_list = ", ".join(sorted(dict.fromkeys(missing_files)))
        return False, f"runtime-ready use-case docs are missing: {missing_list}"
    return True, ""


def _parse_canonical_use_case_ids(text: str) -> list[str]:
    matches = re.findall(r"^(?:- |## )(UC-\d+)\.\s+.+$", text, flags=re.MULTILINE)
    return list(dict.fromkeys(match.strip() for match in matches))


def _looks_like_placeholder(text: str) -> bool:
    placeholder_markers = (
        "TBD from confirmed requirements",
        "See canonical source",
        "To be derived",
    )
    return any(marker in text for marker in placeholder_markers)


def _read_optional(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""
